### PR TITLE
Use only present tense in change notes

### PR DESCRIPTION
**Pull request by mkondratek**

### CODE REVIEW

**Comment by PawelLipski** [comment]
Huh I wouldn't modify the existing change notes tho 🤔 rather won't break anything, but still...

**Comment by PawelLipski** [comment]
As a primitive remedy, I'd ban `ed`-ending words in CHANGE-NOTES since the current release with a script 😅

**Comment by PawelLipski** [comment]
As a primitive remedy, I'd ban `ed`-ending words in CHANGE-NOTES since the current release with a script 😅

**Comment by mkondratek** [comment]
We still have things like 
> Allow checkout and rebase on detach**ed** state
I do not think a script could manage that (well, a simple script ofc)

**Comment by PawelLipski** [comment]
> We still have things like

Meh in fact I'd leave past tense as it is, for the sake of sticking to _local conventions_

**Pull request closed without merging**
