### PR TITLE
Change property name from headless to virtualDisplay

### PR DESCRIPTION
**Pull request by MaciejG604**

### CODE REVIEW

**Review by mkondratek — COMMENTED** [review]
docker/Dockerfile:
`# Tools necessary to run non-headless UI tests in the screen-less environment of CI`

any chance that we want to reword this one btw?

**Comment by MaciejG604** [comment]
If I understand [THIS](https://virtuslab.github.io/tips/#testing/dummy-linux-display) correctly then it actually IS non-headless, but screen-less. Do you mean reword screen-less to virtual display to keep it consistent?

**Comment by mkondratek** [comment]
yup

**Comment by PawelLipski** [comment]
> Do you mean reword screen-less to virtual display to keep it consistent?
+1, I'd avoid using the word _screen-less_ as well as it's somewhat confusing (if _screen_ == _physical display_ then it's okay, but this "==" isn't obvious)

**Review by PawelLipski — APPROVED** [review]

**Pull request merged**
